<a href="https://colab.research.google.com/github/vista33/DataEngineering/blob/main/Intermediate_Data_Type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part A
### Basic mathematic operations

In [ ]:
# Make two variables
a = 12
b = 5

# 1
# addition between two variables
total = a + b
print (f'a + b = {total}')

# subraction between two variables
subtracting = a - b
print (f'a - b = {subtracting}')

# 2
# multiplication between two variables
multiplication = a * b
print (f'a x b = {multiplication}')

# division between two variables
division = a / b
print (f'a : b = {division}')

# 3
# floor division between two variables
floor_division = a // b
print (f'a // b = {floor_division}')

# modulus between two variables
modulus = a % b
print (f'a % b = {modulus}')

# 4
# exponent between two variables
exponent = a ** b
print (f'a ^ b = {exponent}')

a + b = 17
a - b = 7
a x b = 60
a : b = 2.4
a // b = 2
a % b = 2
a ^ b = 248832

# Part B
### Data structure exploration

In [ ]:
# 1. List exploration
# Make a fruits list
fruits = ['apple', 'grape', 'mango', 'strawberry']
print (f'fruits list : {fruits}')

# Add a new fruit into the list
fruits. append ('orange')
print (f'fruits list after append : {fruits}')

# Show the length of the list
print (f'the length of fruits list : {len(fruits)}')

fruits list : ['apple', 'grape', 'mango', 'strawberry']
fruits list after append : ['apple', 'grape', 'mango', 'strawberry', 'orange']
the length of fruits list : 5

In [ ]:
# 2. Tuple exploration
# Make a cities tuple
cities = ('Amsterdam', 'Rotterdam', 'Den Haag', 'Nijmegen', 'Utrecht')
print (f'The cities tuple is {cities}')

# Show the second city in the tuple
second_city = cities [1]
print (f'The second city in the tuple is {second_city}')

The cities tuple is ('Amsterdam', 'Rotterdam', 'Den Haag', 'Nijmegen', 'Utrecht')
The second city in the tuple is Rotterdam

In [ ]:
# 3. Set exploration
# Make a ood-number set using set comprehension
ood_num = {x for x in range (10) if x % 2 == 1}

# Add a new number in the ood-number set
ood_num.add (11)

# Show the ood-number set
print (f'The ood number set : {ood_num}')

The ood number set : {1, 3, 5, 7, 9, 11}

In [ ]:
# 4. Dictionary exploration
# Make a dict about student data
student = {
    'name' : 'Vista',
    'age' : 18,
    'major' : 'Data Engineering'
}

# Access the major
print (f"The major of this student is {student ['major']}")

The major of this student is Data Engineering

# Part C
### Data Frame Exploration and Manipulation

In [ ]:
# 1. Identify continue and categorical data
# Import pandas library
import pandas as pd

# Read csv as a dataframe
df = pd.read_csv ('/content/train_and_test.csv')
print (df.columns)

# Clean the data
df = df [['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'Pclass', 'Embarked', '2urvived']]
df = df.rename (columns = {'2urvived':'Survived'})
df.head(5)

Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', '2urvived'],
      dtype='object')

   Passengerid   Age     Fare  Sex  sibsp  Pclass  Embarked  Survived
0            1  22.0   7.2500    0      1       3       2.0         0
1            2  38.0  71.2833    1      1       1       0.0         1
2            3  26.0   7.9250    1      0       3       2.0         1
3            4  35.0  53.1000    1      1       1       2.0         1
4            5  35.0   8.0500    0      0       3       2.0         0

### Information about the parameters in dataframe
1. Passengerid = Unique identifier for each passenger
2. Age = Age of passenger
3. Fare = Ticket fare paid
4. Sex = Passenger's gender
5. sibsp = Number of siblings/spouses aboard the Titanic with the passenger
6. Parch = Number of parents/children aboard Titanic with the passenger
7. Pclass = Ticket class (1st, 2nd, 3rd)
8. Embarked = Port of embarkation
9. Survived = Survived pasenger (0 = did not survive, 1 = survived)

Based on the information of the parameters in the dataframe,

Based on the columns information:
1.  **Passengerid**, **Sex** and **Embarked** are qualitative data and categorized as **nominal data** because they show the label / identity and can not be compared between one and another.
2. **Pclass** and **Survived** are qualitative data and categorized as **ordinal data** because they can be sorted or ranked.
3. **Age** and **Fare** are quantitative data and categorized as **continuos data** because they can be measured and can be in decimal form.
4. **Parch** and **sibsp** are quantitative data and categorized as **discrete data** because they can be counted and have no decimal form.

In [ ]:
# 2. Looping implementation in dataframe
# Count total children, adult, and elder using for loop
total_children = 0
total_adult = 0
total_elderly = 0
for i in df['Age']:
  if i <= 17:
    total_children += 1
  elif i <= 60:
    total_adult +=1
  else:
    total_elderly += 1

print (f'Total passenger who are children {total_children}, adult {total_adult}, and elder {total_elderly}')

# Make a function to categorize age
def category_age (x):
  if x <= 17:
    y = "Children"
  elif x <= 60:
    y = "Adult"
  else:
    y = "Elderly"
  return y

# Manipulate data by making a new column to show the age category
df['age_category'] = df['Age'].map (category_age)

# Count the survived passenger using while loop
n = 0
while i < len (df):
  if df.loc[i,'Survived'] == 1:
    n += 1
  i += 1
print (f'Total survived passengers is {n}.')

Total passenger who are children 154, adult 1122, and elder 33
   Passengerid   Age     Fare  Sex  sibsp  Pclass  Embarked  Survived  \
0            1  22.0   7.2500    0      1       3       2.0         0
1            2  38.0  71.2833    1      1       1       0.0         1
2            3  26.0   7.9250    1      0       3       2.0         1
3            4  35.0  53.1000    1      1       1       2.0         1
4            5  35.0   8.0500    0      0       3       2.0         0

  age_category
0        Adult
1        Adult
2        Adult
3        Adult
4        Adult
Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'Pclass', 'Embarked',
       'Survived', 'age_category'],
      dtype='object')
Total survived passengers is 328.

In [ ]:
# 3. Data manipulation with lambda function
# Make lambda function to show sex category
sex_category = lambda x : 'Female' if x == 0 else 'Male'
df['sex_category'] = df['Sex'].map (sex_category)
df.head(5)

# make lamda function to show age category
age_category = lambda x : "Children" if x <= 18 else "Adult" if x <=60 else "Elderly"
df['age_category'] = df['Age'].map(age_category)
df.head(5)

,Passengerid,Age,Fare,Sex,sibsp,Pclass,Embarked,Survived,age_category,sex_category
0,1,22.0,7.2500,0,1,3,2.0,0,Adult,Female
1,2,38.0,71.2833,1,1,1,0.0,1,Adult,Male
2,3,26.0,7.9250,1,0,3,2.0,1,Adult,Male
3,4,35.0,53.1000,1,1,1,2.0,1,Adult,Male
4,5,35.0,8.0500,0,0,3,2.0,0,Adult,Female